'use client'

import { useState } from 'react'
import {
  Database, Key, Link2, Info, AlertTriangle, Hash,
} from 'lucide-react'
import { cn } from '@/lib/utils'
import { DocLayout  } from '@/components/doc/DocLayout'
import { DocSection } from '@/components/doc/DocSection'
import { DocTable, DocTableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/doc/DocTable'
import { Badge } from '@/components/ui/badge'

// ─── Lang ─────────────────────────────────────────────────────────────────────

type Lang = 'en' | 'ua'

function LangSwitcher({ lang, onChange }: { lang: Lang; onChange: (l: Lang) => void }) {
  return (
    <div className="flex items-center gap-0.5 rounded-lg border border-border bg-muted p-0.5">
      {(['en', 'ua'] as Lang[]).map((l) => (
        <button key={l} onClick={() => onChange(l)}
          className={['px-2.5 py-1 rounded-md text-xs font-semibold transition-colors',
            lang === l ? 'bg-background text-foreground shadow-sm' : 'text-muted-foreground hover:text-foreground',
          ].join(' ')}
        >{l.toUpperCase()}</button>
      ))}
    </div>
  )
}

// ─── Types ────────────────────────────────────────────────────────────────────

interface I18n { en: string; ua: string }

type ColType = 'pk' | 'fk' | 'col' | 'idx'

interface Column {
  name: string
  type: string
  nullable: boolean
  kind: ColType
  desc: I18n
}

interface TableDef {
  name: string
  desc: I18n
  columns: Column[]
  indexes?: I18n[]
  notes?: I18n[]
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function InfoCard({ children }: { children: React.ReactNode }) {
  return (
    <div className="border border-border bg-card shadow-card rounded-2xl px-4 py-3 flex items-start gap-3 mb-6">
      <Info className="size-4 shrink-0 mt-0.5 text-muted-foreground" />
      <div className="text-sm text-foreground leading-relaxed">{children}</div>
    </div>
  )
}

function WarnCard({ children }: { children: React.ReactNode }) {
  return (
    <div className="border border-warning/30 bg-warning-bg rounded-2xl px-4 py-3 flex items-start gap-3 mb-4">
      <AlertTriangle className="size-4 shrink-0 mt-0.5 text-warning" />
      <div className="text-sm text-foreground leading-relaxed">{children}</div>
    </div>
  )
}

const kindStyle: Record<ColType, { label: string; badge: string }> = {
  pk:  { label: 'PK',  badge: 'bg-violet-500/10 text-violet-500 border-violet-500/30' },
  fk:  { label: 'FK',  badge: 'bg-sky-500/10 text-sky-500 border-sky-500/30'          },
  col: { label: '',    badge: ''                                                        },
  idx: { label: 'IDX', badge: 'bg-amber-500/10 text-amber-500 border-amber-500/30'    },
}

// ─── Data ─────────────────────────────────────────────────────────────────────

const TABLES: TableDef[] = [
  {
    name: 'transactions',
    desc: {
      en: 'Central table. Every deposit or withdrawal attempt creates one row. Never deleted -- audit trail.',
      ua: 'Центральна таблиця. Кожна спроба депозиту або виведення створює один рядок. Ніколи не видаляється -- аудит-трейл.',
    },
    columns: [
      { name: 'id',               type: 'uuid',        nullable: false, kind: 'pk',  desc: { en: 'Primary key, generated by backend (UUID v4)', ua: 'Первинний ключ, генерується бекендом (UUID v4)' } },
      { name: 'brand_id',         type: 'uuid',        nullable: false, kind: 'fk',  desc: { en: 'References brands.id -- which tenant owns this transaction', ua: 'Посилається на brands.id -- який тенант є власником транзакції' } },
      { name: 'user_id',          type: 'uuid',        nullable: false, kind: 'fk',  desc: { en: 'References users.id -- which player initiated it', ua: 'Посилається на users.id -- який гравець ініціював' } },
      { name: 'psp_config_id',    type: 'uuid',        nullable: true,  kind: 'fk',  desc: { en: 'References psp_configs.id -- which PSP handled it. NULL until PSP is selected by orchestrator.', ua: 'Посилається на psp_configs.id -- який PSP обробив. NULL до вибору PSP оркестратором.' } },
      { name: 'direction',        type: "enum('deposit','withdrawal')", nullable: false, kind: 'col', desc: { en: 'Direction of funds flow', ua: 'Напрямок руху коштів' } },
      { name: 'status',           type: 'varchar(32)', nullable: false, kind: 'idx', desc: { en: 'Current UnifiedStatus: INITIATED | PROCESSING | PENDING_CONFIRMATION | PENDING_PARTIAL | COMPLETED | FAILED | TIMED_OUT | CANCELLED', ua: 'Поточний UnifiedStatus: INITIATED | PROCESSING | PENDING_CONFIRMATION | PENDING_PARTIAL | COMPLETED | FAILED | TIMED_OUT | CANCELLED' } },
      { name: 'method',           type: 'varchar(32)', nullable: false, kind: 'col', desc: { en: 'Payment method slug (e.g. "btc", "usdt_trc20")', ua: 'Slug платіжного методу (наприклад, "btc", "usdt_trc20")' } },
      { name: 'amount_requested', type: 'bigint',      nullable: false, kind: 'col', desc: { en: 'Amount requested by player, in the smallest unit of currency (e.g. cents for USD/EUR)', ua: 'Сума запрошена гравцем, в мінімальних одиницях валюти (наприклад, центи для USD/EUR)' } },
      { name: 'amount_credited',  type: 'bigint',      nullable: true,  kind: 'col', desc: { en: 'Final amount credited to player balance, in the smallest unit of currency. NULL until COMPLETED.', ua: 'Фінальна сума зарахована на баланс гравця, в мінімальних одиницях валюти. NULL до COMPLETED.' } },
      { name: 'amount_crypto',    type: 'varchar(64)', nullable: true,  kind: 'col', desc: { en: 'Raw crypto amount as returned by PSP (string to preserve precision)', ua: 'Сира крипто-сума як повернута PSP (рядок для збереження точності)' } },
      { name: 'currency',         type: 'varchar(8)',  nullable: false, kind: 'col', desc: { en: 'ISO 4217 currency code (e.g. "USD")', ua: 'Код валюти ISO 4217 (наприклад, "USD")' } },
      { name: 'fee_total',        type: 'bigint',      nullable: true,  kind: 'col', desc: { en: 'Total fees in the smallest unit of currency (feeService + feeNetwork from PSP). NULL until settled.', ua: 'Загальні комісії в мінімальних одиницях валюти (feeService + feeNetwork від PSP). NULL до розрахунку.' } },
      { name: 'exchange_rate',    type: 'numeric(18,8)',nullable: true, kind: 'col', desc: { en: 'USD/crypto rate used at time of conversion. Store for audit.', ua: 'Курс USD/крипта використаний при конвертації. Зберігати для аудиту.' } },
      { name: 'psp_payment_id',   type: 'varchar(128)',nullable: true,  kind: 'idx', desc: { en: 'PSP-internal transaction ID (e.g. PassimPay transactionId). Used for idempotency and reconciliation.', ua: 'Внутрішній ID транзакції PSP (наприклад, PassimPay transactionId). Використовується для ідемпотентності та reconciliation.' } },
      { name: 'psp_order_id',     type: 'varchar(128)',nullable: true,  kind: 'idx', desc: { en: 'Merchant order ID sent to PSP (derived from id, max 64 chars, PSP-safe charset)', ua: 'ID ордеру мерчанта надісланий у PSP (похідний від id, макс 64 символи, PSP-safe charset)' } },
      { name: 'blockchain_tx_id', type: 'varchar(128)',nullable: true,  kind: 'col', desc: { en: 'On-chain transaction hash. Set on COMPLETED.', ua: 'Хеш on-chain транзакції. Встановлюється при COMPLETED.' } },
      { name: 'wallet_address',   type: 'varchar(256)',nullable: true,  kind: 'col', desc: { en: 'Crypto address shown to player (deposit) or sent to (withdrawal)', ua: 'Крипто-адреса показана гравцю (депозит) або на яку відправлено (виведення)' } },
      { name: 'destination_tag',  type: 'varchar(64)', nullable: true,  kind: 'col', desc: { en: 'Destination tag / memo for XRP, TON networks. NULL for other networks.', ua: 'Destination tag / memo для мереж XRP, TON. NULL для інших мереж.' } },
      { name: 'session_id',       type: 'varchar(128)',nullable: true,  kind: 'idx', desc: { en: 'Player session ID from JWT at time of creation. Used for fraud correlation.', ua: 'ID сесії гравця з JWT на момент створення. Використовується для кореляції фроду.' } },
      { name: 'geo',              type: 'varchar(2)',  nullable: true,  kind: 'col', desc: { en: 'ISO 3166-1 alpha-2 country code at time of transaction', ua: 'Код країни ISO 3166-1 alpha-2 на момент транзакції' } },
      { name: 'metadata',         type: 'jsonb',       nullable: true,  kind: 'col', desc: { en: 'Arbitrary key-value pairs passed from frontend. Not queried -- store only.', ua: 'Довільні пари ключ-значення передані з фронтенду. Не запитуються -- лише зберігаються.' } },
      { name: 'expires_at',       type: 'timestamptz', nullable: true,  kind: 'col', desc: { en: 'Invoice / address expiry time. Used by TTL job to mark TIMED_OUT.', ua: 'Час закінчення інвойсу / адреси. Використовується TTL job для позначення TIMED_OUT.' } },
      { name: 'created_at',       type: 'timestamptz', nullable: false, kind: 'idx', desc: { en: 'Row creation timestamp (UTC)', ua: 'Timestamp створення рядка (UTC)' } },
      { name: 'updated_at',       type: 'timestamptz', nullable: false, kind: 'col', desc: { en: 'Last status change timestamp (UTC). Updated on every status transition.', ua: 'Timestamp останньої зміни статусу (UTC). Оновлюється при кожному переході статусу.' } },
      { name: 'completed_at',     type: 'timestamptz', nullable: true,  kind: 'col', desc: { en: 'Set when status becomes COMPLETED. Used for settlement reporting.', ua: 'Встановлюється коли статус стає COMPLETED. Використовується для звітності по розрахункам.' } },
    ],
    indexes: [
      { en: 'UNIQUE (psp_payment_id) -- idempotency guard', ua: 'UNIQUE (psp_payment_id) -- захист ідемпотентності' },
      { en: 'UNIQUE (psp_order_id) -- no duplicate PSP orders', ua: 'UNIQUE (psp_order_id) -- без дублюючих ордерів PSP' },
      { en: 'INDEX (user_id, created_at DESC) -- player history', ua: 'INDEX (user_id, created_at DESC) -- історія гравця' },
      { en: 'INDEX (brand_id, status, created_at) -- ops dashboard', ua: 'INDEX (brand_id, status, created_at) -- дашборд ops' },
      { en: 'INDEX (status, expires_at) -- TTL job query', ua: 'INDEX (status, expires_at) -- запит TTL job' },
      { en: 'INDEX (psp_config_id, status) -- reconciliation job', ua: 'INDEX (psp_config_id, status) -- reconciliation job' },
    ],
    notes: [
      { en: 'All monetary amounts stored as bigint in the smallest unit of currency (cents for USD/EUR, yen for JPY, etc.). Never use float for money. Always pair amount with its currency column.', ua: 'Всі грошові суми зберігаються як bigint в мінімальних одиницях валюти (центи для USD/EUR, єни для JPY тощо). Ніколи не використовувати float для грошей. Завжди зберігати суму разом з колонкою currency.' },
      { en: 'status column uses application-level enum (varchar), not DB enum -- easier to add new values without migrations.', ua: 'Колонка status використовує enum на рівні застосунку (varchar), не DB enum -- простіше додавати нові значення без міграцій.' },
      { en: 'Rows are never deleted. Hard deletes are prohibited. Use status=CANCELLED for cancellations.', ua: 'Рядки ніколи не видаляються. Жорсткі видалення заборонені. Використовувати status=CANCELLED для скасувань.' },
    ],
  },
  {
    name: 'transaction_events',
    desc: {
      en: 'Immutable event log. Every status transition and webhook is appended here. Enables full audit trail and debugging.',
      ua: 'Незмінний журнал подій. Кожен перехід статусу та webhook додається сюди. Забезпечує повний аудит-трейл та відлагодження.',
    },
    columns: [
      { name: 'id',             type: 'uuid',        nullable: false, kind: 'pk',  desc: { en: 'Primary key', ua: 'Первинний ключ' } },
      { name: 'transaction_id', type: 'uuid',        nullable: false, kind: 'fk',  desc: { en: 'References transactions.id', ua: 'Посилається на transactions.id' } },
      { name: 'event_type',     type: 'varchar(64)', nullable: false, kind: 'idx', desc: { en: 'e.g. status_changed | webhook_received | reconciliation_check | ttl_expired', ua: 'наприклад, status_changed | webhook_received | reconciliation_check | ttl_expired' } },
      { name: 'status_from',    type: 'varchar(32)', nullable: true,  kind: 'col', desc: { en: 'Previous status (NULL for the first event)', ua: 'Попередній статус (NULL для першої події)' } },
      { name: 'status_to',      type: 'varchar(32)', nullable: true,  kind: 'col', desc: { en: 'New status after this event', ua: 'Новий статус після цієї події' } },
      { name: 'payload',        type: 'jsonb',       nullable: true,  kind: 'col', desc: { en: 'Raw webhook body or internal event data', ua: 'Сирий webhook body або дані внутрішньої події' } },
      { name: 'psp_raw',        type: 'jsonb',       nullable: true,  kind: 'col', desc: { en: 'Raw PSP response (for debugging). Strip sensitive fields before storing.', ua: 'Сира відповідь PSP (для відлагодження). Видаляти чутливі поля перед збереженням.' } },
      { name: 'created_at',     type: 'timestamptz', nullable: false, kind: 'idx', desc: { en: 'Event timestamp (UTC)', ua: 'Timestamp події (UTC)' } },
    ],
    notes: [
      { en: 'Append-only. Never update or delete rows.', ua: 'Тільки додавання. Ніколи не оновлювати та не видаляти рядки.' },
      { en: 'Every webhook received must be logged here before processing, even duplicates.', ua: 'Кожен отриманий webhook має бути залоговано тут до обробки, навіть дублікати.' },
    ],
  },
  {
    name: 'psp_configs',
    desc: {
      en: 'One row per PSP per brand per geo. The orchestrator reads this table to select which PSP to use for a given request. Managed via Admin Panel (Phase 4) -- no code deploys needed to add or disable a PSP.',
      ua: 'Один рядок на PSP на бренд на гео. Оркестратор читає цю таблицю для вибору PSP для конкретного запиту. Керується через Admin Panel (Фаза 4) -- не потрібні деплої для додавання або вимкнення PSP.',
    },
    columns: [
      { name: 'id',               type: 'uuid',        nullable: false, kind: 'pk',  desc: { en: 'Primary key', ua: 'Первинний ключ' } },
      { name: 'brand_id',         type: 'uuid',        nullable: false, kind: 'fk',  desc: { en: 'References brands.id', ua: 'Посилається на brands.id' } },
      { name: 'psp_name',         type: 'varchar(64)', nullable: false, kind: 'idx', desc: { en: 'Adapter identifier (e.g. "passimpay"). Must match the adapter registry key.', ua: 'Ідентифікатор адаптера (наприклад, "passimpay"). Повинен відповідати ключу в реєстрі адаптерів.' } },
      { name: 'is_active',        type: 'boolean',     nullable: false, kind: 'idx', desc: { en: 'Toggle to enable/disable PSP without deleting config. Checked by orchestrator.', ua: 'Перемикач для увімкнення/вимкнення PSP без видалення конфігу. Перевіряється оркестратором.' } },
      { name: 'priority',         type: 'smallint',    nullable: false, kind: 'col', desc: { en: 'Cascade priority order. Lower number = tried first. Must be unique per brand+geo+direction.', ua: 'Порядок пріоритету каскаду. Менше число = спробується першим. Повинен бути унікальним на бренд+гео+напрямок.' } },
      { name: 'geo',              type: 'varchar(2)',  nullable: true,  kind: 'idx', desc: { en: 'ISO 3166-1 alpha-2 country filter. NULL = all geos.', ua: 'Фільтр країни ISO 3166-1 alpha-2. NULL = всі гео.' } },
      { name: 'direction',        type: "enum('deposit','withdrawal','both')", nullable: false, kind: 'col', desc: { en: 'Which direction this config applies to', ua: 'На який напрямок поширюється цей конфіг' } },
      { name: 'methods',          type: 'varchar[]',   nullable: false, kind: 'col', desc: { en: 'Array of supported method slugs for this config (e.g. ["btc","usdt_trc20"])', ua: 'Масив slug\'ів підтримуваних методів для цього конфігу (наприклад, ["btc","usdt_trc20"])' } },
      { name: 'credentials',      type: 'jsonb',       nullable: false, kind: 'col', desc: { en: 'Encrypted PSP credentials (platform_id, api_secret etc.). Encrypted at rest -- never returned in API responses.', ua: 'Зашифровані облікові дані PSP (platform_id, api_secret тощо). Зашифровані в спокої -- ніколи не повертаються в API відповідях.' } },
      { name: 'min_amount',       type: 'bigint',      nullable: true,  kind: 'col', desc: { en: 'Override minimum amount in the smallest unit of the config currency. NULL = use PSP default.', ua: 'Перевизначення мінімальної суми в мінімальних одиницях валюти конфігу. NULL = використовувати дефолт PSP.' } },
      { name: 'max_amount',       type: 'bigint',      nullable: true,  kind: 'col', desc: { en: 'Override maximum amount in the smallest unit of the config currency. NULL = use PSP default.', ua: 'Перевизначення максимальної суми в мінімальних одиницях валюти конфігу. NULL = використовувати дефолт PSP.' } },
      { name: 'health_score',     type: 'smallint',    nullable: false, kind: 'col', desc: { en: 'PSP health 0--100. Updated by reconciliation job based on success rate. Used for smart routing in Phase 6.', ua: 'Здоров\'я PSP 0--100. Оновлюється reconciliation job на основі success rate. Використовується для розумного роутингу у Фазі 6.' } },
      { name: 'created_at',       type: 'timestamptz', nullable: false, kind: 'col', desc: { en: 'Row creation timestamp', ua: 'Timestamp створення рядка' } },
      { name: 'updated_at',       type: 'timestamptz', nullable: false, kind: 'col', desc: { en: 'Last update timestamp', ua: 'Timestamp останнього оновлення' } },
    ],
    indexes: [
      { en: 'INDEX (brand_id, is_active, geo, direction) -- orchestrator routing query', ua: 'INDEX (brand_id, is_active, geo, direction) -- запит роутингу оркестратора' },
      { en: 'UNIQUE (brand_id, psp_name, geo, direction) -- no duplicate configs', ua: 'UNIQUE (brand_id, psp_name, geo, direction) -- без дублюючих конфігів' },
    ],
    notes: [
      { en: 'credentials column must be encrypted at rest (e.g. pgcrypto or application-level AES-256). Never log credentials.', ua: 'Колонка credentials повинна бути зашифрована в спокої (наприклад, pgcrypto або AES-256 на рівні застосунку). Ніколи не логувати credentials.' },
      { en: 'health_score starts at 100 and decays on failures. Phase 6 feature -- populated but not used in routing until Phase 6.', ua: 'health_score починається з 100 та знижується при невдачах. Функція Фази 6 -- заповнюється але не використовується в роутингу до Фази 6.' },
    ],
  },
  {
    name: 'routing_rules',
    desc: {
      en: 'Explicit overrides on top of psp_configs priority. Allows ops to pin specific PSPs for specific conditions without changing priority order. Evaluated by orchestrator after base PSP selection.',
      ua: 'Явні перевизначення поверх пріоритету psp_configs. Дозволяє ops закріплювати конкретні PSP для конкретних умов без зміни порядку пріоритетів. Обчислюється оркестратором після базового вибору PSP.',
    },
    columns: [
      { name: 'id',            type: 'uuid',        nullable: false, kind: 'pk',  desc: { en: 'Primary key', ua: 'Первинний ключ' } },
      { name: 'brand_id',      type: 'uuid',        nullable: false, kind: 'fk',  desc: { en: 'References brands.id. NULL = applies to all brands.', ua: 'Посилається на brands.id. NULL = застосовується до всіх брендів.' } },
      { name: 'psp_config_id', type: 'uuid',        nullable: false, kind: 'fk',  desc: { en: 'References psp_configs.id -- which PSP this rule forces', ua: 'Посилається на psp_configs.id -- який PSP це правило примушує використовувати' } },
      { name: 'condition_geo', type: 'varchar(2)',  nullable: true,  kind: 'col', desc: { en: 'ISO 3166-1 alpha-2. NULL = match any geo.', ua: 'ISO 3166-1 alpha-2. NULL = збіг з будь-яким гео.' } },
      { name: 'condition_method', type: 'varchar(32)', nullable: true, kind: 'col', desc: { en: 'Method slug filter. NULL = match any method.', ua: 'Фільтр slug методу. NULL = збіг з будь-яким методом.' } },
      { name: 'condition_currency', type: 'varchar(8)', nullable: true, kind: 'col', desc: { en: 'Currency code filter. NULL = match any currency.', ua: 'Фільтр коду валюти. NULL = збіг з будь-якою валютою.' } },
      { name: 'condition_min_amount', type: 'bigint', nullable: true, kind: 'col', desc: { en: 'Rule applies only when transaction amount >= this value (smallest unit of transaction currency)', ua: 'Правило застосовується лише коли сума транзакції >= цього значення (мінімальні одиниці валюти транзакції)' } },
      { name: 'condition_max_amount', type: 'bigint', nullable: true, kind: 'col', desc: { en: 'Rule applies only when transaction amount <= this value (smallest unit of transaction currency)', ua: 'Правило застосовується лише коли сума транзакції <= цього значення (мінімальні одиниці валюти транзакції)' } },
      { name: 'is_active',     type: 'boolean',     nullable: false, kind: 'idx', desc: { en: 'Toggle rule on/off without deleting', ua: 'Вмикати/вимикати правило без видалення' } },
      { name: 'priority',      type: 'smallint',    nullable: false, kind: 'col', desc: { en: 'Rule evaluation order. Lower = evaluated first. First matching rule wins.', ua: 'Порядок обчислення правил. Менше = обчислюється першим. Перше правило що збіглось -- виграє.' } },
      { name: 'created_at',    type: 'timestamptz', nullable: false, kind: 'col', desc: { en: 'Row creation timestamp', ua: 'Timestamp створення рядка' } },
    ],
    notes: [
      { en: 'Phase 2 feature -- table is created in Phase 1 but the orchestrator only reads it from Phase 2 onwards.', ua: 'Функція Фази 2 -- таблиця створюється у Фазі 1 але оркестратор читає її лише з Фази 2.' },
      { en: 'All NULL conditions are treated as wildcards (match anything). A rule with all NULLs matches every transaction.', ua: 'Всі NULL умови розглядаються як wildcards (збіг з будь-чим). Правило з усіма NULL збігається з кожною транзакцією.' },
    ],
  },
  {
    name: 'payment_methods',
    desc: {
      en: 'Cache of available payment methods per PSP config. Populated by the getSupportedMethods() adapter call. Refreshed every 5 minutes. Frontend reads this to build the method selector.',
      ua: 'Кеш доступних платіжних методів на PSP конфіг. Заповнюється викликом адаптера getSupportedMethods(). Оновлюється кожні 5 хвилин. Фронтенд читає це для побудови вибору методу.',
    },
    columns: [
      { name: 'id',             type: 'uuid',        nullable: false, kind: 'pk',  desc: { en: 'Primary key', ua: 'Первинний ключ' } },
      { name: 'psp_config_id',  type: 'uuid',        nullable: false, kind: 'fk',  desc: { en: 'References psp_configs.id', ua: 'Посилається на psp_configs.id' } },
      { name: 'slug',           type: 'varchar(32)', nullable: false, kind: 'idx', desc: { en: 'Method identifier (e.g. "btc", "usdt_trc20"). Used in transaction.method column.', ua: 'Ідентифікатор методу (наприклад, "btc", "usdt_trc20"). Використовується в колонці transaction.method.' } },
      { name: 'name',           type: 'varchar(64)', nullable: false, kind: 'col', desc: { en: 'Display name for UI (e.g. "Bitcoin", "USDT TRC20")', ua: 'Відображувана назва для UI (наприклад, "Bitcoin", "USDT TRC20")' } },
      { name: 'network',        type: 'varchar(64)', nullable: true,  kind: 'col', desc: { en: 'Blockchain network name (e.g. "TRC20", "ERC20")', ua: 'Назва блокчейн мережі (наприклад, "TRC20", "ERC20")' } },
      { name: 'min_amount',     type: 'bigint',      nullable: false, kind: 'col', desc: { en: 'Minimum amount in the smallest unit of the method currency', ua: 'Мінімальна сума в мінімальних одиницях валюти методу' } },
      { name: 'max_amount',     type: 'bigint',      nullable: false, kind: 'col', desc: { en: 'Maximum amount in the smallest unit of the method currency', ua: 'Максимальна сума в мінімальних одиницях валюти методу' } },
      { name: 'fee_pct',        type: 'numeric(5,2)',nullable: true,  kind: 'col', desc: { en: 'Estimated fee percentage 0.00--100.00', ua: 'Орієнтовний відсоток комісії 0.00--100.00' } },
      { name: 'logo_url',       type: 'varchar(512)',nullable: true,  kind: 'col', desc: { en: 'URL to method logo image', ua: 'URL зображення логотипу методу' } },
      { name: 'requires_tag',   type: 'boolean',     nullable: false, kind: 'col', desc: { en: 'True for XRP, TON and other networks requiring destination tag / memo', ua: 'True для XRP, TON та інших мереж, що вимагають destination tag / memo' } },
      { name: 'is_active',      type: 'boolean',     nullable: false, kind: 'col', desc: { en: 'Soft toggle. False = hide from player UI without deleting cache row.', ua: 'М\'який перемикач. False = приховати з UI гравця без видалення рядка кешу.' } },
      { name: 'cached_at',      type: 'timestamptz', nullable: false, kind: 'col', desc: { en: 'When this row was last refreshed from PSP', ua: 'Коли цей рядок востаннє оновлювався з PSP' } },
    ],
    indexes: [
      { en: 'UNIQUE (psp_config_id, slug) -- one row per method per PSP config', ua: 'UNIQUE (psp_config_id, slug) -- один рядок на метод на PSP конфіг' },
      { en: 'INDEX (psp_config_id, is_active) -- frontend method list query', ua: 'INDEX (psp_config_id, is_active) -- запит списку методів для фронтенду' },
    ],
  },
]

// ─── Relationships ────────────────────────────────────────────────────────────

const RELATIONS: { from: string; to: string; col: string; desc: I18n }[] = [
  { from: 'transactions',    to: 'brands',       col: 'brand_id',      desc: { en: 'Each transaction belongs to a brand (tenant)', ua: 'Кожна транзакція належить бренду (тенанту)' } },
  { from: 'transactions',    to: 'users',        col: 'user_id',       desc: { en: 'Each transaction belongs to a player', ua: 'Кожна транзакція належить гравцю' } },
  { from: 'transactions',    to: 'psp_configs',  col: 'psp_config_id', desc: { en: 'Which PSP handled this transaction (set by orchestrator)', ua: 'Який PSP обробив цю транзакцію (встановлюється оркестратором)' } },
  { from: 'transaction_events', to: 'transactions', col: 'transaction_id', desc: { en: 'Event log entries belong to a transaction', ua: 'Записи журналу подій належать транзакції' } },
  { from: 'psp_configs',     to: 'brands',       col: 'brand_id',      desc: { en: 'PSP configs are scoped to a brand', ua: 'PSP конфіги прив\'язані до бренду' } },
  { from: 'routing_rules',   to: 'brands',       col: 'brand_id',      desc: { en: 'Routing rules are scoped to a brand (nullable = all brands)', ua: 'Правила роутингу прив\'язані до бренду (nullable = всі бренди)' } },
  { from: 'routing_rules',   to: 'psp_configs',  col: 'psp_config_id', desc: { en: 'Rule forces a specific PSP config', ua: 'Правило примушує використовувати конкретний PSP конфіг' } },
  { from: 'payment_methods', to: 'psp_configs',  col: 'psp_config_id', desc: { en: 'Methods are cached per PSP config', ua: 'Методи кешуються на PSP конфіг' } },
]

// ─── Components ───────────────────────────────────────────────────────────────

function TableCard({ table, lang }: { table: TableDef; lang: Lang }) {
  const ua = lang === 'ua'
  const pkCols  = table.columns.filter(c => c.kind === 'pk').length
  const fkCols  = table.columns.filter(c => c.kind === 'fk').length
  const idxCols = table.columns.filter(c => c.kind === 'idx').length

  return (
    <div className="border border-border rounded-2xl overflow-hidden">
      {/* Header */}
      <div className="px-4 py-3 bg-muted border-b border-border flex items-center gap-3">
        <div className="flex size-7 shrink-0 items-center justify-center rounded-xl bg-background text-muted-foreground">
          <Database className="size-3.5" />
        </div>
        <code className="text-sm font-mono font-bold text-foreground">{table.name}</code>
        <div className="flex items-center gap-1.5 ml-auto">
          <span className="text-xs text-muted-foreground tabular-nums">{table.columns.length} {ua ? 'колонок' : 'columns'}</span>
          {pkCols > 0  && <Badge variant="outline" className="text-xs bg-violet-500/10 text-violet-500 border-violet-500/30 pointer-events-none">PK</Badge>}
          {fkCols > 0  && <Badge variant="outline" className="text-xs bg-sky-500/10 text-sky-500 border-sky-500/30 pointer-events-none">{fkCols} FK</Badge>}
          {idxCols > 0 && <Badge variant="outline" className="text-xs bg-amber-500/10 text-amber-500 border-amber-500/30 pointer-events-none">{idxCols} IDX</Badge>}
        </div>
      </div>

      <div className="bg-card px-4 py-3 border-b border-border">
        <p className="text-sm text-muted-foreground leading-relaxed">{table.desc[lang]}</p>
      </div>

      {/* Columns */}
      <DocTable>
        <DocTableHeader>
          <TableRow>
            <TableHead>{ua ? 'Колонка' : 'Column'}</TableHead>
            <TableHead>{ua ? 'Тип' : 'Type'}</TableHead>
            <TableHead>{ua ? 'Nullable' : 'Nullable'}</TableHead>
            <TableHead>{ua ? 'Опис' : 'Description'}</TableHead>
          </TableRow>
        </DocTableHeader>
        <TableBody>
          {table.columns.map(col => {
            const k = kindStyle[col.kind]
            return (
              <TableRow key={col.name}>
                <TableCell>
                  <div className="flex items-center gap-1.5">
                    {col.kind !== 'col' && (
                      <Badge variant="outline" className={cn('text-xs pointer-events-none shrink-0', k.badge)}>{k.label}</Badge>
                    )}
                    <code className="text-xs font-mono text-foreground">{col.name}</code>
                  </div>
                </TableCell>
                <TableCell><code className="text-xs font-mono text-muted-foreground">{col.type}</code></TableCell>
                <TableCell>
                  {col.nullable
                    ? <Badge variant="outline" className="text-xs bg-muted text-muted-foreground border-border pointer-events-none">{ua ? 'Так' : 'Yes'}</Badge>
                    : <Badge variant="outline" className="text-xs bg-destructive-bg text-destructive border-destructive/30 pointer-events-none">{ua ? 'Ні' : 'No'}</Badge>}
                </TableCell>
                <TableCell className="text-sm text-muted-foreground">{col.desc[lang]}</TableCell>
              </TableRow>
            )
          })}
        </TableBody>
      </DocTable>

      {/* Indexes */}
      {table.indexes && table.indexes.length > 0 && (
        <div className="px-4 py-3 border-t border-border bg-muted/50">
          <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-2">
            {ua ? 'Індекси' : 'Indexes'}
          </p>
          <div className="flex flex-col gap-1">
            {table.indexes.map((idx, i) => (
              <div key={i} className="flex items-start gap-2">
                <Hash className="size-3 shrink-0 mt-0.5 text-muted-foreground/50" />
                <code className="text-xs text-muted-foreground leading-snug">{idx[lang]}</code>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Notes */}
      {table.notes && table.notes.length > 0 && (
        <div className="px-4 py-3 border-t border-border">
          <div className="flex flex-col gap-2">
            {table.notes.map((note, i) => (
              <div key={i} className="flex items-start gap-2 rounded-xl bg-muted px-3 py-2">
                <Info className="size-3.5 shrink-0 mt-0.5 text-muted-foreground" />
                <p className="text-xs text-muted-foreground leading-snug">{note[lang]}</p>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function Page() {
  const [lang, setLang] = useState<Lang>('en')
  const ua = lang === 'ua'

  return (
    <DocLayout
      title="Data Model"
      breadcrumbLabel="Payment module"
      breadcrumbHref="/sandbox/payment-architecture"
      parentCrumb={{ label: 'Sandbox', href: '/sandbox' }}
      description={ua
        ? 'Схема таблиць бази даних платіжного модуля. Phase 0 артефакт.'
        : 'Database table schema for the payment module. Phase 0 artifact.'}
      tags={[
        { label: 'Phase 0',    type: 'tag'    },
        { label: 'Spec',       type: 'status' },
        { label: 'PostgreSQL', type: 'tag'    },
      ]}
      titleExtra={<LangSwitcher lang={lang} onChange={setLang} />}
      footnote="DEPO44 | DATA MODEL v1 | PHASE 0 ARCHITECTURE"
    >

      {/* ── Intro ─────────────────────────────────────────────────────────── */}
      <InfoCard>
        {ua
          ? <>5 таблиць платіжного модуля. Всі таблиці створюються у <strong>Phase 1</strong> (навіть якщо деякі колонки/функції використовуються пізніше). PostgreSQL. Грошові суми -- завжди <code className="text-xs bg-muted rounded px-1.5 py-0.5">bigint</code> в мінімальних одиницях відповідної валюти (для USD -- центи, для EUR -- центи, для JPY -- єни). Валюта зберігається поруч у колонці <code className="text-xs bg-muted rounded px-1.5 py-0.5">currency</code> (ISO 4217). Система підтримує мультивалютність: баланси та транзакції можуть бути у різних валютах.</>
          : <>5 tables of the payment module. All tables are created in <strong>Phase 1</strong> (even if some columns/features are used later). PostgreSQL. Monetary amounts -- always <code className="text-xs bg-muted rounded px-1.5 py-0.5">bigint</code> in the smallest unit of the respective currency (cents for USD/EUR, yen for JPY, etc.). The currency is stored alongside in the <code className="text-xs bg-muted rounded px-1.5 py-0.5">currency</code> column (ISO 4217). Multi-currency is supported: balances and transactions can be in different currencies.</>
        }
      </InfoCard>

      <WarnCard>
        {ua
          ? <><code className="text-xs bg-muted rounded px-1.5 py-0.5">brands</code> та <code className="text-xs bg-muted rounded px-1.5 py-0.5">users</code> таблиці тут не описані -- вони належать до модуля авторизації. Таблиці нижче лише посилаються на них через FK.</>
          : <><code className="text-xs bg-muted rounded px-1.5 py-0.5">brands</code> and <code className="text-xs bg-muted rounded px-1.5 py-0.5">users</code> tables are not described here -- they belong to the auth module. The tables below only reference them via FK.</>
        }
      </WarnCard>

      {/* ── Section 1: Tables ─────────────────────────────────────────────── */}
      <DocSection num="1" title={ua ? 'Таблиці' : 'Tables'}>
        <div className="flex flex-col gap-8">
          {TABLES.map(table => (
            <TableCard key={table.name} table={table} lang={lang} />
          ))}
        </div>
      </DocSection>

      {/* ── Section 2: Relationships ──────────────────────────────────────── */}
      <div className="mt-8">
        <DocSection num="2" title={ua ? 'Зв\'язки між таблицями' : 'Table Relationships'}>
          <DocTable>
            <DocTableHeader>
              <TableRow>
                <TableHead>{ua ? 'Таблиця' : 'Table'}</TableHead>
                <TableHead>{ua ? 'Колонка' : 'Column'}</TableHead>
                <TableHead>{ua ? 'Посилається на' : 'References'}</TableHead>
                <TableHead>{ua ? 'Опис' : 'Description'}</TableHead>
              </TableRow>
            </DocTableHeader>
            <TableBody>
              {RELATIONS.map((r, i) => (
                <TableRow key={i}>
                  <TableCell><code className="text-xs font-mono bg-muted rounded px-1.5 py-0.5">{r.from}</code></TableCell>
                  <TableCell><code className="text-xs font-mono text-sky-500">{r.col}</code></TableCell>
                  <TableCell><code className="text-xs font-mono bg-muted rounded px-1.5 py-0.5">{r.to}</code></TableCell>
                  <TableCell className="text-sm text-muted-foreground">{r.desc[lang]}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </DocTable>
        </DocSection>
      </div>

    </DocLayout>
  )
}
