'use client'

import { useState } from 'react'
import {
  Plug, ArrowRight, Code2, Globe, AlertTriangle, Shield,
  Info, CheckCircle2, ChevronRight,
} from 'lucide-react'
import { cn } from '@/lib/utils'
import { DocLayout  } from '@/components/doc/DocLayout'
import { DocSection } from '@/components/doc/DocSection'
import { DocTable, DocTableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/doc/DocTable'
import { Badge } from '@/components/ui/badge'

// ─── Lang ─────────────────────────────────────────────────────────────────────

type Lang = 'en' | 'ua'

function LangSwitcher({ lang, onChange }: { lang: Lang; onChange: (l: Lang) => void }) {
  return (
    <div className="flex items-center gap-0.5 rounded-lg border border-border bg-muted p-0.5">
      {(['en', 'ua'] as Lang[]).map((l) => (
        <button
          key={l}
          onClick={() => onChange(l)}
          className={[
            'px-2.5 py-1 rounded-md text-xs font-semibold transition-colors',
            lang === l ? 'bg-background text-foreground shadow-sm' : 'text-muted-foreground hover:text-foreground',
          ].join(' ')}
        >
          {l.toUpperCase()}
        </button>
      ))}
    </div>
  )
}

// ─── Types ────────────────────────────────────────────────────────────────────

interface I18n { en: string; ua: string }

// ─── Code block ───────────────────────────────────────────────────────────────

function CodeBlock({ code, label }: { code: string; label?: string }) {
  return (
    <div className="rounded-2xl border border-border overflow-hidden">
      {label && (
        <div className="flex items-center gap-2 px-4 py-2 border-b border-border bg-muted">
          <Code2 className="size-3.5 text-muted-foreground" />
          <span className="text-xs font-semibold text-muted-foreground">{label}</span>
        </div>
      )}
      <pre className="bg-card px-4 py-4 overflow-x-auto text-xs leading-relaxed text-foreground font-mono whitespace-pre">
        {code.trim()}
      </pre>
    </div>
  )
}

// ─── Section intro card ───────────────────────────────────────────────────────

function InfoCard({ text }: { text: string }) {
  return (
    <div className="border border-border bg-card shadow-card rounded-2xl px-4 py-3 flex items-start gap-3 mb-6">
      <Info className="size-4 shrink-0 mt-0.5 text-muted-foreground" />
      <p className="text-sm text-foreground leading-relaxed">{text}</p>
    </div>
  )
}

// ─── Method contract ──────────────────────────────────────────────────────────

interface MethodField {
  name: string
  type: string
  required: boolean
  desc: I18n
}

interface MethodDef {
  signature: string
  returns: string
  desc: I18n
  inputs: MethodField[]
  outputs: MethodField[]
  errors: string[]
  notes: I18n[]
}

const METHODS: MethodDef[] = [
  {
    signature: 'initiateDeposit(req: DepositRequest)',
    returns: 'Promise<UnifiedResponse>',
    desc: {
      en: 'Creates a deposit session with the PSP. Returns a redirect URL or crypto address for the player.',
      ua: 'Створює сесію депозиту у PSP. Повертає URL для редиректу або крипто-адресу для гравця.',
    },
    inputs: [
      { name: 'payment_id',   type: 'string',        required: true,  desc: { en: 'Unique idempotency key, generated by orchestrator',       ua: 'Унікальний ключ ідемпотентності, згенерований оркестратором' } },
      { name: 'user_id',      type: 'string',        required: true,  desc: { en: 'Player identifier',                                       ua: 'Ідентифікатор гравця' } },
      { name: 'brand_id',     type: 'string',        required: true,  desc: { en: 'Brand / tenant identifier',                               ua: 'Ідентифікатор бренду / тенанта' } },
      { name: 'amount',       type: 'number',        required: true,  desc: { en: 'Amount in USD cents (integer)',                           ua: 'Сума в центах USD (ціле число)' } },
      { name: 'currency',     type: 'string',        required: true,  desc: { en: 'ISO 4217 currency code (e.g. "USD")',                     ua: 'Код валюти ISO 4217 (наприклад, "USD")' } },
      { name: 'method',       type: 'string',        required: true,  desc: { en: 'Payment method slug (e.g. "btc", "usdt_trc20")',          ua: 'Slug платіжного методу (наприклад, "btc", "usdt_trc20")' } },
      { name: 'return_url',   type: 'string',        required: false, desc: { en: 'URL to redirect player after payment (if PSP supports)', ua: 'URL для редиректу гравця після оплати (якщо PSP підтримує)' } },
      { name: 'metadata',     type: 'Record<string, string>', required: false, desc: { en: 'Arbitrary key-value pairs passed through to webhook events', ua: 'Довільні пари ключ-значення, що передаються у webhook-події' } },
    ],
    outputs: [
      { name: 'payment_id',     type: 'string',           required: true,  desc: { en: 'Echo of the input payment_id',                        ua: 'Відлуння вхідного payment_id' } },
      { name: 'psp_payment_id', type: 'string',           required: true,  desc: { en: 'PSP-internal transaction identifier (store for idempotency)', ua: 'Внутрішній ідентифікатор транзакції PSP (зберігати для ідемпотентності)' } },
      { name: 'status',         type: 'UnifiedStatus',    required: true,  desc: { en: 'Always INITIATED at this stage',                     ua: 'Завжди INITIATED на цьому етапі' } },
      { name: 'action',         type: 'UnifiedAction',    required: true,  desc: { en: 'redirect | show_address | show_qr',                  ua: 'redirect | show_address | show_qr' } },
      { name: 'redirect_url',   type: 'string | null',    required: false, desc: { en: 'Set when action = redirect',                         ua: 'Встановлюється коли action = redirect' } },
      { name: 'address',        type: 'string | null',    required: false, desc: { en: 'Crypto address, set when action = show_address',     ua: 'Крипто-адреса, встановлюється коли action = show_address' } },
      { name: 'tag',            type: 'string | null',    required: false, desc: { en: 'Destination tag / memo (XRP, TON etc.)',              ua: 'Destination tag / memo (XRP, TON тощо)' } },
      { name: 'expires_at',     type: 'string | null',    required: false, desc: { en: 'ISO 8601 expiry timestamp (for invoice methods)',    ua: 'Timestamp закінчення в ISO 8601 (для invoice-методів)' } },
    ],
    errors: ['PSP_UNAVAILABLE', 'INVALID_METHOD', 'AMOUNT_BELOW_MIN', 'AMOUNT_ABOVE_MAX', 'CURRENCY_NOT_SUPPORTED'],
    notes: [
      { en: 'Must be idempotent: calling with the same payment_id twice must return the same response without creating a second PSP transaction.', ua: 'Має бути ідемпотентним: виклик з тим самим payment_id двічі повинен повертати ту саму відповідь без створення другої транзакції PSP.' },
      { en: 'If PSP requires amount in crypto, the adapter is responsible for the USD -- crypto conversion before the request.', ua: 'Якщо PSP вимагає суму в крипті, адаптер відповідає за конвертацію USD -- крипта перед запитом.' },
    ],
  },
  {
    signature: 'initiateWithdrawal(req: WithdrawalRequest)',
    returns: 'Promise<UnifiedResponse>',
    desc: {
      en: 'Submits a withdrawal request to the PSP. Funds are sent to the player\'s blockchain address.',
      ua: 'Надсилає запит на виведення до PSP. Кошти відправляються на блокчейн-адресу гравця.',
    },
    inputs: [
      { name: 'payment_id',      type: 'string', required: true,  desc: { en: 'Unique idempotency key',                                  ua: 'Унікальний ключ ідемпотентності' } },
      { name: 'user_id',         type: 'string', required: true,  desc: { en: 'Player identifier',                                       ua: 'Ідентифікатор гравця' } },
      { name: 'brand_id',        type: 'string', required: true,  desc: { en: 'Brand / tenant identifier',                               ua: 'Ідентифікатор бренду / тенанта' } },
      { name: 'amount',          type: 'number', required: true,  desc: { en: 'Amount in USD cents (integer)',                           ua: 'Сума в центах USD (ціле число)' } },
      { name: 'currency',        type: 'string', required: true,  desc: { en: 'ISO 4217 currency code',                                  ua: 'Код валюти ISO 4217' } },
      { name: 'method',          type: 'string', required: true,  desc: { en: 'Payment method slug',                                     ua: 'Slug платіжного методу' } },
      { name: 'wallet_address',  type: 'string', required: true,  desc: { en: 'Player\'s destination wallet address',                   ua: 'Адреса гаманця гравця-отримувача' } },
      { name: 'tag',             type: 'string', required: false, desc: { en: 'Destination tag / memo (required for XRP, TON)',         ua: 'Destination tag / memo (обов\'язковий для XRP, TON)' } },
    ],
    outputs: [
      { name: 'payment_id',     type: 'string',        required: true,  desc: { en: 'Echo of the input payment_id',                    ua: 'Відлуння вхідного payment_id' } },
      { name: 'psp_payment_id', type: 'string',        required: true,  desc: { en: 'PSP-internal transaction identifier',             ua: 'Внутрішній ідентифікатор транзакції PSP' } },
      { name: 'status',         type: 'UnifiedStatus', required: true,  desc: { en: 'INITIATED or PROCESSING depending on PSP',       ua: 'INITIATED або PROCESSING залежно від PSP' } },
    ],
    errors: ['PSP_UNAVAILABLE', 'INVALID_WALLET_ADDRESS', 'AMOUNT_BELOW_MIN', 'AMOUNT_ABOVE_MAX', 'INSUFFICIENT_PSP_BALANCE'],
    notes: [
      { en: 'Adapter must convert USD amount to crypto before calling PSP if required.', ua: 'Адаптер повинен конвертувати суму USD в крипту перед викликом PSP якщо потрібно.' },
      { en: 'Idempotency is critical -- duplicate calls must not send funds twice.', ua: 'Ідемпотентність є критичною -- повторні виклики не повинні відправляти кошти двічі.' },
    ],
  },
  {
    signature: 'getTransactionStatus(psp_payment_id: string)',
    returns: 'Promise<UnifiedStatusResponse>',
    desc: {
      en: 'Polls the PSP for the current transaction status. Used by the reconciliation job for stuck transactions.',
      ua: 'Поллить PSP для отримання поточного статусу транзакції. Використовується reconciliation job для застряглих транзакцій.',
    },
    inputs: [
      { name: 'psp_payment_id', type: 'string', required: true, desc: { en: 'PSP-internal transaction ID returned by initiate* methods', ua: 'Внутрішній ID транзакції PSP, повернутий методами initiate*' } },
    ],
    outputs: [
      { name: 'psp_payment_id',  type: 'string',        required: true,  desc: { en: 'Echo of the input identifier',               ua: 'Відлуння вхідного ідентифікатора' } },
      { name: 'status',          type: 'UnifiedStatus', required: true,  desc: { en: 'Current unified status',                    ua: 'Поточний unified статус' } },
      { name: 'amount_credited', type: 'number | null', required: false, desc: { en: 'Final credited amount in USD cents',        ua: 'Фінальна зарахована сума в центах USD' } },
      { name: 'blockchain_tx_id',type: 'string | null', required: false, desc: { en: 'On-chain transaction hash if available',    ua: 'Хеш on-chain транзакції якщо доступний' } },
    ],
    errors: ['PSP_UNAVAILABLE', 'TRANSACTION_NOT_FOUND'],
    notes: [
      { en: 'This method is for reconciliation only -- not for real-time UI updates. Use webhooks + status polling for UI.', ua: 'Цей метод лише для reconciliation -- не для оновлення UI в реальному часі. Для UI використовувати webhooks + status polling.' },
    ],
  },
  {
    signature: 'handleWebhook(payload: RawWebhookPayload)',
    returns: 'Promise<UnifiedEvent>',
    desc: {
      en: 'Parses and verifies a raw webhook from the PSP. Returns a normalized event the orchestrator can act on.',
      ua: 'Парсить та верифікує сирий webhook від PSP. Повертає нормалізовану подію, на яку може реагувати оркестратор.',
    },
    inputs: [
      { name: 'body',      type: 'unknown',           required: true, desc: { en: 'Raw parsed JSON body of the webhook request',          ua: 'Сирий розпарсений JSON body webhook-запиту' } },
      { name: 'headers',   type: 'Record<string, string>', required: true, desc: { en: 'HTTP headers (needed for signature verification)', ua: 'HTTP заголовки (потрібні для верифікації підпису)' } },
      { name: 'raw_body',  type: 'Buffer',            required: true, desc: { en: 'Raw unmodified request body bytes for HMAC verification', ua: 'Сирі необроблені байти тіла запиту для HMAC-верифікації' } },
    ],
    outputs: [
      { name: 'event_type',      type: 'UnifiedEventType', required: true,  desc: { en: 'deposit_confirmed | deposit_processing | withdrawal_completed | withdrawal_failed | partial_payment', ua: 'deposit_confirmed | deposit_processing | withdrawal_completed | withdrawal_failed | partial_payment' } },
      { name: 'psp_payment_id',  type: 'string',           required: true,  desc: { en: 'PSP transaction identifier',                ua: 'Ідентифікатор транзакції PSP' } },
      { name: 'status',          type: 'UnifiedStatus',    required: true,  desc: { en: 'New transaction status',                    ua: 'Новий статус транзакції' } },
      { name: 'amount_credited', type: 'number | null',    required: false, desc: { en: 'Amount to credit in USD cents (deposits)',  ua: 'Сума для зарахування в центах USD (депозити)' } },
      { name: 'amount_debited',  type: 'number | null',    required: false, desc: { en: 'Amount debited in USD cents (withdrawals)', ua: 'Сума списана в центах USD (виведення)' } },
      { name: 'fee_total',       type: 'number | null',    required: false, desc: { en: 'Total fees in USD cents',                   ua: 'Загальні комісії в центах USD' } },
      { name: 'blockchain_tx_id',type: 'string | null',    required: false, desc: { en: 'On-chain transaction hash',                 ua: 'Хеш on-chain транзакції' } },
    ],
    errors: ['INVALID_SIGNATURE', 'UNKNOWN_EVENT_TYPE', 'MALFORMED_PAYLOAD'],
    notes: [
      { en: 'Adapter MUST verify the PSP signature before processing. Throw INVALID_SIGNATURE if it fails -- the gateway returns 400 to PSP.', ua: 'Адаптер ЗОБОВ\'ЯЗАНИЙ верифікувати підпис PSP перед обробкою. Кидати INVALID_SIGNATURE якщо не збігається -- шлюз повертає 400 до PSP.' },
      { en: 'Adapter must return 200 quickly. Heavy processing (balance updates) happens in the orchestrator after this method returns.', ua: 'Адаптер повинен швидко повернути 200. Важка обробка (оновлення балансу) відбувається в оркестраторі після повернення цього методу.' },
    ],
  },
  {
    signature: 'getSupportedMethods(geo: string, currency: string)',
    returns: 'Promise<PaymentMethod[]>',
    desc: {
      en: 'Returns the list of payment methods this PSP supports for the given country and currency.',
      ua: 'Повертає список платіжних методів, які цей PSP підтримує для заданої країни та валюти.',
    },
    inputs: [
      { name: 'geo',      type: 'string', required: true, desc: { en: 'ISO 3166-1 alpha-2 country code (e.g. "UA", "DE")', ua: 'Код країни ISO 3166-1 alpha-2 (наприклад, "UA", "DE")' } },
      { name: 'currency', type: 'string', required: true, desc: { en: 'ISO 4217 currency code (e.g. "USD")',              ua: 'Код валюти ISO 4217 (наприклад, "USD")' } },
    ],
    outputs: [
      { name: 'slug',       type: 'string',  required: true,  desc: { en: 'Method identifier used in initiate* calls (e.g. "btc", "usdt_trc20")', ua: 'Ідентифікатор методу для initiate* викликів (наприклад, "btc", "usdt_trc20")' } },
      { name: 'name',       type: 'string',  required: true,  desc: { en: 'Human-readable name for UI display',                                   ua: 'Зрозуміла назва для відображення в UI' } },
      { name: 'min_amount', type: 'number',  required: true,  desc: { en: 'Minimum deposit/withdrawal amount in USD cents',                       ua: 'Мінімальна сума депозиту/виведення в центах USD' } },
      { name: 'max_amount', type: 'number',  required: true,  desc: { en: 'Maximum deposit/withdrawal amount in USD cents',                       ua: 'Максимальна сума депозиту/виведення в центах USD' } },
      { name: 'fee_pct',    type: 'number',  required: false, desc: { en: 'Estimated fee percentage (0--100)',                                    ua: 'Орієнтовний відсоток комісії (0--100)' } },
      { name: 'logo_url',   type: 'string',  required: false, desc: { en: 'URL to method logo image',                                            ua: 'URL зображення логотипу методу' } },
    ],
    errors: ['PSP_UNAVAILABLE'],
    notes: [
      { en: 'Result may be cached per geo+currency for up to 5 minutes to reduce PSP API calls.', ua: 'Результат може кешуватись по geo+currency до 5 хвилин для зменшення кількості викликів API PSP.' },
    ],
  },
]

// ─── TypeScript types ─────────────────────────────────────────────────────────

const TS_INTERFACE = `
// IPaymentProvider -- implement this interface for every PSP adapter

export interface IPaymentProvider {
  initiateDeposit(req: DepositRequest): Promise<UnifiedResponse>
  initiateWithdrawal(req: WithdrawalRequest): Promise<UnifiedResponse>
  getTransactionStatus(psp_payment_id: string): Promise<UnifiedStatusResponse>
  handleWebhook(payload: RawWebhookPayload): Promise<UnifiedEvent>
  getSupportedMethods(geo: string, currency: string): Promise<PaymentMethod[]>
}
`.trim()

const TS_TYPES = `
// ── Request types ──────────────────────────────────────────────────────────────

export interface DepositRequest {
  payment_id:   string                      // idempotency key
  user_id:      string
  brand_id:     string
  amount:       number                      // USD cents, integer
  currency:     string                      // ISO 4217
  method:       string                      // e.g. "btc", "usdt_trc20"
  return_url?:  string
  metadata?:    Record<string, string>
}

export interface WithdrawalRequest {
  payment_id:      string                   // idempotency key
  user_id:         string
  brand_id:        string
  amount:          number                   // USD cents, integer
  currency:        string                   // ISO 4217
  method:          string
  wallet_address:  string
  tag?:            string                   // required for XRP, TON
}

export interface RawWebhookPayload {
  body:      unknown
  headers:   Record<string, string>
  raw_body:  Buffer                         // for HMAC verification
}

// ── Response types ─────────────────────────────────────────────────────────────

export interface UnifiedResponse {
  payment_id:      string
  psp_payment_id:  string
  status:          UnifiedStatus
  action:          UnifiedAction
  redirect_url?:   string | null
  address?:        string | null
  tag?:            string | null
  expires_at?:     string | null            // ISO 8601
}

export interface UnifiedStatusResponse {
  psp_payment_id:   string
  status:           UnifiedStatus
  amount_credited?: number | null           // USD cents
  blockchain_tx_id?:string | null
}

export interface UnifiedEvent {
  event_type:       UnifiedEventType
  psp_payment_id:   string
  status:           UnifiedStatus
  amount_credited?: number | null           // USD cents
  amount_debited?:  number | null           // USD cents
  fee_total?:       number | null           // USD cents
  blockchain_tx_id?:string | null
}

export interface PaymentMethod {
  slug:        string
  name:        string
  min_amount:  number                       // USD cents
  max_amount:  number                       // USD cents
  fee_pct?:    number                       // 0--100
  logo_url?:   string
}

// ── Enums ──────────────────────────────────────────────────────────────────────

export type UnifiedStatus =
  | 'INITIATED'
  | 'PROCESSING'
  | 'PENDING_CONFIRMATION'
  | 'PENDING_PARTIAL'
  | 'COMPLETED'
  | 'FAILED'
  | 'TIMED_OUT'
  | 'CANCELLED'

export type UnifiedAction =
  | 'redirect'
  | 'show_address'
  | 'show_qr'

export type UnifiedEventType =
  | 'deposit_confirmed'
  | 'deposit_processing'
  | 'withdrawal_completed'
  | 'withdrawal_failed'
  | 'partial_payment'
`.trim()

const TS_ERROR = `
export class UnifiedPaymentError extends Error {
  constructor(
    public readonly code: UnifiedErrorCode,
    public readonly message: string,
    public readonly psp_raw?: unknown,      // original PSP error for logging
  ) {
    super(message)
  }
}

export type UnifiedErrorCode =
  | 'PSP_UNAVAILABLE'           // PSP returned 5xx or timed out
  | 'INVALID_METHOD'            // method not supported for this geo/currency
  | 'AMOUNT_BELOW_MIN'          // amount < method minimum
  | 'AMOUNT_ABOVE_MAX'          // amount > method maximum
  | 'CURRENCY_NOT_SUPPORTED'    // PSP does not support this currency
  | 'INVALID_WALLET_ADDRESS'    // wallet address failed validation
  | 'INSUFFICIENT_PSP_BALANCE'  // PSP account balance too low for withdrawal
  | 'TRANSACTION_NOT_FOUND'     // psp_payment_id not found at PSP
  | 'INVALID_SIGNATURE'         // webhook HMAC verification failed
  | 'UNKNOWN_EVENT_TYPE'        // webhook event type not recognized
  | 'MALFORMED_PAYLOAD'         // webhook payload missing required fields
`.trim()

// ─── Frontend API contract ────────────────────────────────────────────────────

interface Endpoint {
  method: 'POST' | 'GET'
  path: string
  desc: I18n
  requestBody?: { field: string; type: string; required: boolean; desc: I18n }[]
  responseBody: { field: string; type: string; desc: I18n }[]
  errorCodes: string[]
}

const ENDPOINTS: Endpoint[] = [
  {
    method: 'POST',
    path: '/api/payments/deposit',
    desc: {
      en: 'Initiates a deposit. Returns the action the frontend must perform (redirect or show address).',
      ua: 'Ініціює депозит. Повертає дію, яку фронтенд повинен виконати (редирект або показати адресу).',
    },
    requestBody: [
      { field: 'amount',    type: 'number', required: true,  desc: { en: 'Amount in USD cents',                                          ua: 'Сума в центах USD' } },
      { field: 'currency',  type: 'string', required: true,  desc: { en: 'ISO 4217 (e.g. "USD")',                                        ua: 'ISO 4217 (наприклад, "USD")' } },
      { field: 'method',    type: 'string', required: true,  desc: { en: 'Payment method slug from getSupportedMethods',                 ua: 'Slug методу з getSupportedMethods' } },
      { field: 'return_url',type: 'string', required: false, desc: { en: 'URL to return player to after payment (for redirect methods)', ua: 'URL для повернення гравця після оплати (для redirect-методів)' } },
    ],
    responseBody: [
      { field: 'payment_id',   type: 'string',       desc: { en: 'Internal transaction ID -- use for status polling',                  ua: 'Внутрішній ID транзакції -- використовувати для status polling' } },
      { field: 'status',       type: 'UnifiedStatus',desc: { en: 'Always "INITIATED"',                                                 ua: 'Завжди "INITIATED"' } },
      { field: 'action',       type: 'string',       desc: { en: '"redirect" | "show_address" | "show_qr"',                            ua: '"redirect" | "show_address" | "show_qr"' } },
      { field: 'redirect_url', type: 'string|null',  desc: { en: 'Redirect the player here when action = "redirect"',                  ua: 'Перенаправити гравця сюди коли action = "redirect"' } },
      { field: 'address',      type: 'string|null',  desc: { en: 'Show this crypto address when action = "show_address" or "show_qr"', ua: 'Показати цю крипто-адресу коли action = "show_address" або "show_qr"' } },
      { field: 'tag',          type: 'string|null',  desc: { en: 'Show destination tag alongside address (XRP, TON). MUST be shown.', ua: 'Показати destination tag поруч з адресою (XRP, TON). ОБОВ\'ЯЗКОВО показати.' } },
      { field: 'expires_at',   type: 'string|null',  desc: { en: 'ISO 8601 expiry -- show countdown timer in UI',                     ua: 'Закінчення в ISO 8601 -- показати таймер зворотного відліку в UI' } },
    ],
    errorCodes: ['400 AMOUNT_BELOW_MIN', '400 AMOUNT_ABOVE_MAX', '400 INVALID_METHOD', '503 PSP_UNAVAILABLE'],
  },
  {
    method: 'POST',
    path: '/api/payments/withdraw',
    desc: {
      en: 'Submits a withdrawal request. Frontend must collect and validate wallet_address before calling this.',
      ua: 'Надсилає запит на виведення. Фронтенд повинен зібрати та валідувати wallet_address перед викликом.',
    },
    requestBody: [
      { field: 'amount',         type: 'number', required: true,  desc: { en: 'Amount in USD cents',                   ua: 'Сума в центах USD' } },
      { field: 'currency',       type: 'string', required: true,  desc: { en: 'ISO 4217',                              ua: 'ISO 4217' } },
      { field: 'method',         type: 'string', required: true,  desc: { en: 'Payment method slug',                   ua: 'Slug платіжного методу' } },
      { field: 'wallet_address', type: 'string', required: true,  desc: { en: 'Player\'s destination wallet address',  ua: 'Адреса гаманця гравця-отримувача' } },
      { field: 'tag',            type: 'string', required: false, desc: { en: 'Destination tag (XRP, TON)',             ua: 'Destination tag (XRP, TON)' } },
    ],
    responseBody: [
      { field: 'payment_id', type: 'string',       desc: { en: 'Internal transaction ID',    ua: 'Внутрішній ID транзакції' } },
      { field: 'status',     type: 'UnifiedStatus',desc: { en: '"INITIATED" or "PROCESSING"', ua: '"INITIATED" або "PROCESSING"' } },
    ],
    errorCodes: ['400 AMOUNT_BELOW_MIN', '400 AMOUNT_ABOVE_MAX', '400 INVALID_WALLET_ADDRESS', '503 PSP_UNAVAILABLE', '503 INSUFFICIENT_PSP_BALANCE'],
  },
  {
    method: 'GET',
    path: '/api/payments/:id/status',
    desc: {
      en: 'Returns the current status of a transaction. Used for frontend polling until a terminal status is reached.',
      ua: 'Повертає поточний статус транзакції. Використовується для frontend polling до досягнення термінального статусу.',
    },
    responseBody: [
      { field: 'payment_id',    type: 'string',       desc: { en: 'Transaction ID',                               ua: 'ID транзакції' } },
      { field: 'status',        type: 'UnifiedStatus',desc: { en: 'Current status',                              ua: 'Поточний статус' } },
      { field: 'amount',        type: 'number|null',  desc: { en: 'Credited/debited amount in USD cents',        ua: 'Зарахована/списана сума в центах USD' } },
      { field: 'method',        type: 'string',       desc: { en: 'Payment method slug',                         ua: 'Slug платіжного методу' } },
      { field: 'created_at',    type: 'string',       desc: { en: 'ISO 8601 creation timestamp',                 ua: 'Timestamp створення в ISO 8601' } },
      { field: 'updated_at',    type: 'string',       desc: { en: 'ISO 8601 last update timestamp',              ua: 'Timestamp останнього оновлення в ISO 8601' } },
    ],
    errorCodes: ['404 TRANSACTION_NOT_FOUND', '403 FORBIDDEN (transaction belongs to another user)'],
  },
  {
    method: 'GET',
    path: '/api/payments/methods',
    desc: {
      en: 'Returns available payment methods for the current player\'s geo and currency. Frontend calls this to build the method selector UI.',
      ua: 'Повертає доступні платіжні методи для поточного гео та валюти гравця. Фронтенд викликає це для побудови UI вибору методу.',
    },
    responseBody: [
      { field: 'methods[]',     type: 'PaymentMethod[]', desc: { en: 'Array of available methods', ua: 'Масив доступних методів' } },
      { field: '.slug',         type: 'string',          desc: { en: 'Use as "method" field in deposit/withdraw calls', ua: 'Використовувати як поле "method" у викликах deposit/withdraw' } },
      { field: '.name',         type: 'string',          desc: { en: 'Display name',                ua: 'Відображувана назва' } },
      { field: '.min_amount',   type: 'number',          desc: { en: 'Minimum in USD cents',        ua: 'Мінімум в центах USD' } },
      { field: '.max_amount',   type: 'number',          desc: { en: 'Maximum in USD cents',        ua: 'Максимум в центах USD' } },
      { field: '.logo_url',     type: 'string|null',     desc: { en: 'Icon URL',                    ua: 'URL іконки' } },
    ],
    errorCodes: ['503 PSP_UNAVAILABLE'],
  },
]

// ─── Adapter rules ────────────────────────────────────────────────────────────

const ADAPTER_RULES: { title: I18n; desc: I18n; Icon: typeof Shield }[] = [
  {
    Icon: Shield,
    title: { en: 'Never expose PSP-native errors', ua: 'Ніколи не розкривати нативні помилки PSP' },
    desc: {
      en: 'Catch all PSP errors, log the raw error internally, and throw UnifiedPaymentError with the appropriate UnifiedErrorCode. The orchestrator must never see PSP-specific error objects.',
      ua: 'Перехоплювати всі помилки PSP, логувати сирі помилки внутрішньо, кидати UnifiedPaymentError з відповідним UnifiedErrorCode. Оркестратор ніколи не повинен бачити PSP-специфічні об\'єкти помилок.',
    },
  },
  {
    Icon: CheckCircle2,
    title: { en: 'Verify webhook signature first, always', ua: 'Завжди спочатку верифікувати підпис webhook' },
    desc: {
      en: 'handleWebhook must verify the PSP signature before parsing any payload fields. Throw INVALID_SIGNATURE immediately if it fails. For PassimPay: HMAC-SHA256(platform_id + ";" + body + ";" + secret, secret) vs x-signature header.',
      ua: 'handleWebhook повинен верифікувати підпис PSP перед парсингом будь-яких полів payload. Кидати INVALID_SIGNATURE одразу якщо не збігається. Для PassimPay: HMAC-SHA256(platform_id + ";" + body + ";" + secret, secret) проти заголовка x-signature.',
    },
  },
  {
    Icon: ArrowRight,
    title: { en: 'Map all statuses to UnifiedStatus', ua: 'Маппити всі статуси у UnifiedStatus' },
    desc: {
      en: 'Every PSP-specific status code or field value must be mapped to one of the eight UnifiedStatus values. Unknown statuses must be logged and mapped to PROCESSING (never silently dropped).',
      ua: 'Кожен PSP-специфічний код статусу або значення поля повинно бути замаплено на одне з восьми значень UnifiedStatus. Невідомі статуси повинні логуватись та маппитись у PROCESSING (ніколи не ігноруватись).',
    },
  },
  {
    Icon: Globe,
    title: { en: 'Normalize all amounts to USD cents', ua: 'Нормалізувати всі суми до центів USD' },
    desc: {
      en: 'PSPs return amounts in crypto. Adapters must convert to USD cents before populating UnifiedEvent or UnifiedResponse fields. Use the exchange rate at the time of conversion and store it for audit.',
      ua: 'PSP повертають суми в крипті. Адаптери повинні конвертувати в центи USD перед заповненням полів UnifiedEvent або UnifiedResponse. Використовувати курс на момент конвертації та зберігати його для аудиту.',
    },
  },
  {
    Icon: CheckCircle2,
    title: { en: 'Be idempotent on initiateDeposit and initiateWithdrawal', ua: 'Бути ідемпотентним у initiateDeposit та initiateWithdrawal' },
    desc: {
      en: 'If the same payment_id arrives twice, return the existing transaction data without creating a new PSP transaction. Store psp_payment_id keyed by payment_id to enable this check.',
      ua: 'Якщо той самий payment_id приходить двічі, повертати дані існуючої транзакції без створення нової транзакції PSP. Зберігати psp_payment_id з ключем payment_id для забезпечення цієї перевірки.',
    },
  },
  {
    Icon: AlertTriangle,
    title: { en: 'Respond 200 to webhooks immediately', ua: 'Відповідати 200 на webhooks негайно' },
    desc: {
      en: 'handleWebhook must return quickly. After signature verification and payload parsing, enqueue the event for the orchestrator and return 200. Do not perform balance updates, DB writes, or external calls inside this method.',
      ua: 'handleWebhook повинен повертати швидко. Після верифікації підпису та парсингу payload, поставити подію в чергу для оркестратора та повернути 200. Не виконувати оновлення балансу, записи в БД або зовнішні виклики всередині цього методу.',
    },
  },
  {
    Icon: Code2,
    title: { en: 'Set timeouts on all outbound PSP calls', ua: 'Встановлювати таймаути на всі вихідні виклики PSP' },
    desc: {
      en: 'All HTTP calls to PSP APIs must have an explicit timeout (recommended: 10s for initiate*, 5s for status). On timeout, throw PSP_UNAVAILABLE -- the orchestrator will handle cascade/retry logic.',
      ua: 'Всі HTTP виклики до API PSP повинні мати явний таймаут (рекомендовано: 10с для initiate*, 5с для status). При таймауті кидати PSP_UNAVAILABLE -- оркестратор обробить логіку cascade/retry.',
    },
  },
]

// ─── Frontend status handling ─────────────────────────────────────────────────

const STATUS_UI: { status: string; colorCls: string; bgCls: string; borderCls: string; label: I18n; uiAction: I18n; terminal: boolean }[] = [
  { status: 'INITIATED',           colorCls: 'text-slate-400',   bgCls: 'bg-muted',           borderCls: 'border-border',           label: { en: 'Initiated',            ua: 'Ініційовано'              }, uiAction: { en: 'Show address / redirect',     ua: 'Показати адресу / редирект'   }, terminal: false },
  { status: 'PROCESSING',          colorCls: 'text-warning',      bgCls: 'bg-warning-bg',      borderCls: 'border-warning/30',       label: { en: 'Processing',           ua: 'В обробці'                }, uiAction: { en: 'Show spinner, keep polling',  ua: 'Показати спіннер, продовжувати polling' }, terminal: false },
  { status: 'PENDING_CONFIRMATION',colorCls: 'text-sky-500',      bgCls: 'bg-sky-500/10',      borderCls: 'border-sky-500/30',       label: { en: 'Awaiting confirmation', ua: 'Очікування підтвердження' }, uiAction: { en: 'Show "waiting for blockchain confirmation"', ua: 'Показати "очікування підтвердження блокчейну"' }, terminal: false },
  { status: 'PENDING_PARTIAL',     colorCls: 'text-violet-500',   bgCls: 'bg-violet-500/10',   borderCls: 'border-violet-500/30',    label: { en: 'Partial payment',      ua: 'Часткова оплата'          }, uiAction: { en: 'Show received amount, explain shortfall', ua: 'Показати отриману суму, пояснити нестачу' }, terminal: false },
  { status: 'COMPLETED',           colorCls: 'text-success',      bgCls: 'bg-success-bg',      borderCls: 'border-success/30',       label: { en: 'Completed',            ua: 'Завершено'                }, uiAction: { en: 'Show success, stop polling',  ua: 'Показати успіх, зупинити polling' }, terminal: true  },
  { status: 'FAILED',              colorCls: 'text-destructive',  bgCls: 'bg-destructive-bg',  borderCls: 'border-destructive/30',   label: { en: 'Failed',               ua: 'Помилка'                  }, uiAction: { en: 'Show error, offer retry',     ua: 'Показати помилку, запропонувати повторити' }, terminal: true  },
  { status: 'TIMED_OUT',           colorCls: 'text-orange-500',   bgCls: 'bg-orange-500/10',   borderCls: 'border-orange-500/30',    label: { en: 'Timed out',            ua: 'Час вийшов'               }, uiAction: { en: 'Show "payment window expired", stop polling', ua: 'Показати "вікно оплати закрилось", зупинити polling' }, terminal: true  },
  { status: 'CANCELLED',           colorCls: 'text-muted-foreground', bgCls: 'bg-muted',       borderCls: 'border-border',           label: { en: 'Cancelled',            ua: 'Скасовано'                }, uiAction: { en: 'Show cancelled state, stop polling', ua: 'Показати скасований стан, зупинити polling' }, terminal: true  },
]

// ─── Components ───────────────────────────────────────────────────────────────

function FieldTable({ fields, lang }: { fields: MethodField[]; lang: Lang }) {
  const ua = lang === 'ua'
  return (
    <DocTable>
      <DocTableHeader>
        <TableRow>
          <TableHead>{ua ? 'Поле' : 'Field'}</TableHead>
          <TableHead>{ua ? 'Тип' : 'Type'}</TableHead>
          <TableHead>{ua ? 'Обов\'язк.' : 'Required'}</TableHead>
          <TableHead>{ua ? 'Опис' : 'Description'}</TableHead>
        </TableRow>
      </DocTableHeader>
      <TableBody>
        {fields.map((f) => (
          <TableRow key={f.name}>
            <TableCell><code className="text-xs bg-muted rounded px-1.5 py-0.5 font-mono">{f.name}</code></TableCell>
            <TableCell><code className="text-xs text-muted-foreground font-mono">{f.type}</code></TableCell>
            <TableCell>
              {f.required
                ? <Badge variant="outline" className="text-xs bg-destructive-bg text-destructive border-destructive/30 pointer-events-none">{ua ? 'Так' : 'Yes'}</Badge>
                : <Badge variant="outline" className="text-xs bg-muted text-muted-foreground border-border pointer-events-none">{ua ? 'Ні' : 'No'}</Badge>}
            </TableCell>
            <TableCell className="text-sm text-muted-foreground">{f.desc[lang]}</TableCell>
          </TableRow>
        ))}
      </TableBody>
    </DocTable>
  )
}

function MethodCard({ m, lang }: { m: MethodDef; lang: Lang }) {
  const ua = lang === 'ua'
  return (
    <div className="border border-border rounded-2xl overflow-hidden">
      {/* Header */}
      <div className="px-4 py-3 bg-muted border-b border-border flex items-start gap-3">
        <div className="flex size-7 shrink-0 items-center justify-center rounded-xl bg-background text-muted-foreground">
          <Plug className="size-3.5" />
        </div>
        <div>
          <code className="text-sm font-mono font-semibold text-foreground">{m.signature}</code>
          <div className="flex items-center gap-1.5 mt-0.5">
            <ChevronRight className="size-3 text-muted-foreground/50" />
            <code className="text-xs font-mono text-muted-foreground">{m.returns}</code>
          </div>
        </div>
      </div>

      <div className="px-4 py-4 flex flex-col gap-5 bg-card">
        <p className="text-sm text-muted-foreground leading-relaxed">{m.desc[lang]}</p>

        {/* Inputs */}
        {m.inputs.length > 0 && (
          <div>
            <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-2">{ua ? 'Вхідні параметри' : 'Input Parameters'}</p>
            <FieldTable fields={m.inputs} lang={lang} />
          </div>
        )}

        {/* Outputs */}
        <div>
          <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-2">{ua ? 'Вихідні поля' : 'Output Fields'}</p>
          <FieldTable fields={m.outputs} lang={lang} />
        </div>

        {/* Errors */}
        <div>
          <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-2">{ua ? 'Можливі помилки' : 'Possible Errors'}</p>
          <div className="flex flex-wrap gap-1.5">
            {m.errors.map(e => (
              <code key={e} className="text-xs bg-destructive-bg text-destructive rounded px-1.5 py-0.5">{e}</code>
            ))}
          </div>
        </div>

        {/* Notes */}
        {m.notes.length > 0 && (
          <div className="flex flex-col gap-2">
            {m.notes.map((n, i) => (
              <div key={i} className="flex items-start gap-2 rounded-xl bg-muted px-3 py-2.5">
                <Info className="size-3.5 shrink-0 mt-0.5 text-muted-foreground" />
                <p className="text-xs text-muted-foreground leading-snug">{n[lang]}</p>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}

function EndpointCard({ ep, lang }: { ep: Endpoint; lang: Lang }) {
  const ua = lang === 'ua'
  const methodColor = ep.method === 'GET' ? 'text-sky-500 bg-sky-500/10 border-sky-500/30' : 'text-success bg-success-bg border-success/30'
  return (
    <div className="border border-border rounded-2xl overflow-hidden">
      <div className="px-4 py-3 bg-muted border-b border-border flex items-center gap-3">
        <Badge variant="outline" className={cn('pointer-events-none font-mono text-xs font-bold shrink-0', methodColor)}>{ep.method}</Badge>
        <code className="text-sm font-mono font-semibold text-foreground">{ep.path}</code>
      </div>
      <div className="px-4 py-4 flex flex-col gap-4 bg-card">
        <p className="text-sm text-muted-foreground leading-relaxed">{ep.desc[lang]}</p>

        {ep.requestBody && (
          <div>
            <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-2">{ua ? 'Тіло запиту' : 'Request Body'}</p>
            <DocTable>
              <DocTableHeader>
                <TableRow>
                  <TableHead>{ua ? 'Поле' : 'Field'}</TableHead>
                  <TableHead>{ua ? 'Тип' : 'Type'}</TableHead>
                  <TableHead>{ua ? 'Обов\'язк.' : 'Req.'}</TableHead>
                  <TableHead>{ua ? 'Опис' : 'Description'}</TableHead>
                </TableRow>
              </DocTableHeader>
              <TableBody>
                {ep.requestBody.map(f => (
                  <TableRow key={f.field}>
                    <TableCell><code className="text-xs bg-muted rounded px-1.5 py-0.5 font-mono">{f.field}</code></TableCell>
                    <TableCell><code className="text-xs text-muted-foreground font-mono">{f.type}</code></TableCell>
                    <TableCell>
                      {f.required
                        ? <Badge variant="outline" className="text-xs bg-destructive-bg text-destructive border-destructive/30 pointer-events-none">{ua ? 'Так' : 'Yes'}</Badge>
                        : <Badge variant="outline" className="text-xs bg-muted text-muted-foreground border-border pointer-events-none">{ua ? 'Ні' : 'No'}</Badge>}
                    </TableCell>
                    <TableCell className="text-sm text-muted-foreground">{f.desc[lang]}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </DocTable>
          </div>
        )}

        <div>
          <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-2">{ua ? 'Відповідь (200)' : 'Response (200)'}</p>
          <DocTable>
            <DocTableHeader>
              <TableRow>
                <TableHead>{ua ? 'Поле' : 'Field'}</TableHead>
                <TableHead>{ua ? 'Тип' : 'Type'}</TableHead>
                <TableHead>{ua ? 'Опис' : 'Description'}</TableHead>
              </TableRow>
            </DocTableHeader>
            <TableBody>
              {ep.responseBody.map(f => (
                <TableRow key={f.field}>
                  <TableCell><code className="text-xs bg-muted rounded px-1.5 py-0.5 font-mono">{f.field}</code></TableCell>
                  <TableCell><code className="text-xs text-muted-foreground font-mono">{f.type}</code></TableCell>
                  <TableCell className="text-sm text-muted-foreground">{f.desc[lang]}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </DocTable>
        </div>

        <div>
          <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-2">{ua ? 'Коди помилок' : 'Error Codes'}</p>
          <div className="flex flex-wrap gap-1.5">
            {ep.errorCodes.map(e => (
              <code key={e} className="text-xs bg-muted rounded px-1.5 py-0.5 text-muted-foreground">{e}</code>
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function Page() {
  const [lang, setLang] = useState<Lang>('en')
  const ua = lang === 'ua'

  return (
    <DocLayout
      title="Unified Interface"
      breadcrumbLabel="Payment Infrastructure"
      breadcrumbHref="/sandbox/payment-infra"
      parentCrumb={{ label: 'Sandbox', href: '/sandbox' }}
      description={ua
        ? 'IPaymentProvider -- єдиний контракт для всіх PSP-адаптерів. Повна спека для бекенду та фронтенду.'
        : 'IPaymentProvider -- a unified contract for all PSP adapters. Full spec for backend and frontend.'}
      tags={[
        { label: 'Phase 1',        type: 'tag'    },
        { label: 'Spec',           type: 'status' },
        { label: 'Backend',        type: 'tag'    },
        { label: 'Frontend',       type: 'tag'    },
      ]}
      titleExtra={<LangSwitcher lang={lang} onChange={setLang} />}
      footnote="DEPO44 | UNIFIED INTERFACE SPEC v1 | PHASE 1"
    >

      {/* ── Intro ─────────────────────────────────────────────────────────── */}
      <InfoCard text={ua
        ? 'Оркестратор ніколи не знає з яким PSP він працює -- він викликає лише методи IPaymentProvider. Кожен PSP-адаптер реалізує цей інтерфейс і несе відповідальність за нормалізацію даних, верифікацію підписів та обробку помилок. Оркестратор ніколи не бачить сирі дані PSP.'
        : 'The orchestrator never knows which PSP it is working with -- it only calls IPaymentProvider methods. Each PSP adapter implements this interface and is responsible for data normalization, signature verification, and error handling. The orchestrator never sees raw PSP data.'}
      />

      {/* ── Section 1: TypeScript types ───────────────────────────────────── */}
      <DocSection num="1" title={ua ? 'TypeScript типи' : 'TypeScript Types'}>
        <div className="flex flex-col gap-4">
          <CodeBlock label="IPaymentProvider interface" code={TS_INTERFACE} />
          <CodeBlock label="Request & Response types" code={TS_TYPES} />
          <CodeBlock label="Error types" code={TS_ERROR} />
        </div>
      </DocSection>

      {/* ── Section 2: Method contracts ───────────────────────────────────── */}
      <div className="mt-8">
        <DocSection num="2" title={ua ? 'Контракти методів' : 'Method Contracts'}>
          <div className="flex flex-col gap-6">
            {METHODS.map(m => (
              <MethodCard key={m.signature} m={m} lang={lang} />
            ))}
          </div>
        </DocSection>
      </div>

      {/* ── Section 3: Frontend API ───────────────────────────────────────── */}
      <div className="mt-8">
        <DocSection num="3" title={ua ? 'HTTP API для фронтенду' : 'Frontend HTTP API'}>
          <div className="border border-border bg-card shadow-card rounded-2xl px-4 py-3 flex items-start gap-3 mb-6">
            <Info className="size-4 shrink-0 mt-0.5 text-muted-foreground" />
            <p className="text-sm text-muted-foreground leading-relaxed">
              {ua
                ? 'Це HTTP-ендпоінти, які фронтенд викликає напряму. Всі вони захищені JWT через Auth & Brand middleware. Всі помилки повертаються у форматі { error: { code: string, message: string }, request_id: string }.'
                : 'These are the HTTP endpoints the frontend calls directly. All are protected by JWT via the Auth & Brand middleware. All errors are returned as { error: { code: string, message: string }, request_id: string }.'}
            </p>
          </div>
          <div className="flex flex-col gap-6">
            {ENDPOINTS.map(ep => (
              <EndpointCard key={ep.path} ep={ep} lang={lang} />
            ))}
          </div>
        </DocSection>
      </div>

      {/* ── Section 4: Frontend status handling ──────────────────────────── */}
      <div className="mt-8">
        <DocSection num="4" title={ua ? 'Обробка статусів на фронтенді' : 'Frontend Status Handling'}>
          <div className="border border-border bg-card shadow-card rounded-2xl px-4 py-3 flex items-start gap-3 mb-6">
            <Info className="size-4 shrink-0 mt-0.5 text-muted-foreground" />
            <p className="text-sm text-muted-foreground leading-relaxed">
              {ua
                ? 'Зупиняти polling при отриманні будь-якого термінального статусу. Продовжувати polling кожні 5--10 секунд для нетермінальних статусів. Рекомендований таймаут polling: 15 хвилин.'
                : 'Stop polling on any terminal status. Continue polling every 5--10 seconds for non-terminal statuses. Recommended polling timeout: 15 minutes.'}
            </p>
          </div>
          <DocTable>
            <DocTableHeader>
              <TableRow>
                <TableHead>{ua ? 'Статус' : 'Status'}</TableHead>
                <TableHead>{ua ? 'Назва' : 'Label'}</TableHead>
                <TableHead>{ua ? 'Дія в UI' : 'UI Action'}</TableHead>
                <TableHead>{ua ? 'Термінальний' : 'Terminal'}</TableHead>
              </TableRow>
            </DocTableHeader>
            <TableBody>
              {STATUS_UI.map(s => (
                <TableRow key={s.status}>
                  <TableCell>
                    <span className={cn('text-xs border rounded px-2 py-0.5 font-mono', s.colorCls, s.bgCls, s.borderCls)}>
                      {s.status}
                    </span>
                  </TableCell>
                  <TableCell className="text-sm text-foreground">{s.label[lang]}</TableCell>
                  <TableCell className="text-sm text-muted-foreground">{s.uiAction[lang]}</TableCell>
                  <TableCell>
                    {s.terminal
                      ? <Badge variant="outline" className="text-xs bg-destructive-bg text-destructive border-destructive/30 pointer-events-none">{ua ? 'Так' : 'Yes'}</Badge>
                      : <Badge variant="outline" className="text-xs bg-muted text-muted-foreground border-border pointer-events-none">{ua ? 'Ні' : 'No'}</Badge>}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </DocTable>
        </DocSection>
      </div>

      {/* ── Section 5: Adapter rules ──────────────────────────────────────── */}
      <div className="mt-8">
        <DocSection num="5" title={ua ? 'Правила реалізації адаптера' : 'Adapter Implementation Rules'}>
          <div className="grid grid-cols-1 gap-4 tablet:grid-cols-2">
            {ADAPTER_RULES.map(({ Icon, title, desc }, i) => (
              <div key={i} className="border border-border bg-card rounded-2xl p-4 flex flex-col gap-2">
                <div className="flex items-start gap-3">
                  <div className="flex size-7 shrink-0 items-center justify-center rounded-xl bg-muted text-muted-foreground">
                    <Icon className="size-3.5" />
                  </div>
                  <p className="text-sm font-semibold text-foreground leading-snug">{title[lang]}</p>
                </div>
                <p className="text-sm text-muted-foreground leading-relaxed pl-10">{desc[lang]}</p>
              </div>
            ))}
          </div>
        </DocSection>
      </div>

    </DocLayout>
  )
}
